// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PATBMS_Web.Data;

#nullable disable

namespace PATBMS_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529011100_AddWardIDToBed")]
    partial class AddWardIDToBed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PATBMS_Web.Models.Admission", b =>
                {
                    b.Property<string>("AdmissionID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmissionType")
                        .HasColumnType("TEXT");

                    b.HasKey("AdmissionID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("PATBMS_Web.Models.Bed", b =>
                {
                    b.Property<string>("BedID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("WardID")
                        .HasColumnType("TEXT");

                    b.HasKey("BedID");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("PATBMS_Web.Models.BedAllocation", b =>
                {
                    b.Property<string>("AllocationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllocationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("AllocationID");

                    b.ToTable("BedAllocations");
                });

            modelBuilder.Entity("PATBMS_Web.Models.DiagnosisRecord", b =>
                {
                    b.Property<string>("DiagnosisID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateRecorded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("TEXT");

                    b.HasKey("DiagnosisID");

                    b.ToTable("DiagnosisRecords");
                });

            modelBuilder.Entity("PATBMS_Web.Models.Discharge", b =>
                {
                    b.Property<string>("DischargeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DischargeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DischargeReason")
                        .HasColumnType("TEXT");

                    b.HasKey("DischargeID");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("PATBMS_Web.Models.HandoverRecord", b =>
                {
                    b.Property<string>("HandoverID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutstandingTasks")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivingDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SendingDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("TEXT");

                    b.HasKey("HandoverID");

                    b.ToTable("HandoverRecords");
                });

            modelBuilder.Entity("PATBMS_Web.Models.Notification", b =>
                {
                    b.Property<string>("NotificationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateSent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PATBMS_Web.Models.Patient", b =>
                {
                    b.Property<string>("PatientID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdmissionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("NHINumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PATBMS_Web.Models.TriageAssessment", b =>
                {
                    b.Property<string>("TriageID")
                        .HasColumnType("TEXT");

                    b.Property<int>("ATSCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptoms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vitals")
                        .HasColumnType("TEXT");

                    b.HasKey("TriageID");

                    b.ToTable("TriageAssessments");
                });

            modelBuilder.Entity("PATBMS_Web.Models.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PATBMS_Web.Models.Ward", b =>
                {
                    b.Property<string>("WardID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WardName")
                        .HasColumnType("TEXT");

                    b.HasKey("WardID");

                    b.ToTable("Wards");
                });
#pragma warning restore 612, 618
        }
    }
}
